DojoSecret/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.validation.urls', namespace = 'login')),
    url(r'^dojo/', include('apps.dojo_secret.urls', namespace = 'secret')),

]

apps/dojo_secret/urls.py
# APP: dojo_secrets
from django.conf.urls import url, include
from . import views
urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name = 'home'),
    url(r'^post$', views.postSecret, name = 'post'),
    url(r'^popular$', views.mostPopular, name = 'popular'),
    url(r'^post/(?P<post_id>\d+)$', views.deleteSecret, name = 'delete'),
    url(r'^like/(?P<post_id>\d+)$', views.likeSecret, name = 'like'),

]

apps/validation/urls.py
# APP: validation
from django.conf.urls import url, include
from . import views
# from django.contrib import admin

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name = 'login'),
    url(r'^validate/(?P<route>(reg|login))$', views.validateUser, name = 'validate'),
    url(r'^logout/$', views.logOut, name = 'logout'),

]

apps/dojo_secret/models.py
from __future__ import unicode_literals
from ..validation.models import User
from django.db import models
from django.db.models import Count

# Create your models here.
class SecretAction(models.Manager):
    def makeSecret(self, POST_data):
        if POST_data['secret']:
            self.create(secrets=POST_data['secret'],writer=User.objects.get(id=POST_data['user_id']))
        return
    def deleteSecret(self, id):
        self.get(id=id).delete()
        return
    def likeSecret(self, user, msg):
        post = Secret.objects.get(id=msg)
        likedBy = User.objects.get(id=user)
        post.likes.add(likedBy)
        return
    def getSecrets(self):
        return self.annotate(numLikes=Count('likes')).all().order_by('-created_at')
    def getPopular(self):
        return self.annotate(numLikes=Count('likes')).all().order_by('-numLikes', '-created_at')[:10]

class Secret(models.Model):
    secrets = models.CharField(max_length=120)
    writer  = models.ForeignKey(User, related_name='user_secrets')
    likes = models.ManyToManyField(User)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now_add = True)
    objects = SecretAction()

apps/validation/models.py
from __future__ import unicode_literals

from django.db import models
import bcrypt
import re

# Create your models here.
class UserAction(models.Manager):
    def newUser(self, POST_data):
        NAME_REGEX = re.compile(r'^[a-zA-Z]{2,}$')
        EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9+_-]+@[a-zA-Z0-9+_-]+\.[a-zA-Z]+$')
        PW_REGEX = re.compile(r'^.{8,}$')
        message = []
        if self.filter(email=POST_data['email']):
            message.append('Account Error: Account already exists for that email')
        if not NAME_REGEX.match(POST_data['first_name']) or not NAME_REGEX.match(POST_data['last_name']):
            message.append('Name error: Name fields must be two or more characters')
        if not EMAIL_REGEX.match(POST_data['email']):
            message.append('Email error: Please enter a valid email')
        if not PW_REGEX.match(POST_data['pw']):
            message.append('Password error: Password must be 8 or more charaters')
        if not POST_data['pw'] == POST_data['pwConf']:
            message.append('Password error: Your passwords do not match')
        if message:
            return message, False
        else:
            hash = bcrypt.hashpw(POST_data['pw'].encode(), bcrypt.gensalt())
            newUser = self.create(first_name=POST_data['first_name'], last_name=POST_data['last_name'], email=POST_data['email'], password=hash)
            return newUser, True
    def validateUser(self, POST_data):
        message = []
        if POST_data['email']:
            email = POST_data['email']
            checkUser = self.filter(email=email)
            if not checkUser:
                message.append('Login error: User account not present')
                return message, False
            elif bcrypt.hashpw(POST_data['pw'].encode(), checkUser[0].password.encode()) == checkUser[0].password:
                    return checkUser[0], True
            else:
                message.append('Password error: Incorrect password')
                return message, False
        else:
            message.append('Email error: Please enter an email')
            return message, False
class User(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    email = models.CharField(max_length=45)
    password = models.CharField(max_length=60)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now_add = True)
    objects = UserAction()
    def __str__(self):
        name = self.first_name + " " + self.last_name
        return name

apps/dojo_secret/views.py
from django.shortcuts import render, redirect, reverse
from .models import Secret
# Create your views here.
def index(request):
    try:
        request.session['user']
    except KeyError:
        return redirect(reverse('login:login'))
    context = {
        'posts': Secret.objects.getSecrets()
    }
    print '-' * 80
    print Secret.objects.filter(likes=request.session['user']['id'])
    return render(request, 'dojo_secret/index.html', context)
    # if request.session['user']:
    # else:

'''calls method to make a secret in DB '''
def postSecret(request):
    if request.POST['secret']:
        Secret.objects.makeSecret(request.POST)
        return redirect('secret:home')
    else:
        return redirect('secret:home')

'''calls method to remove from DB'''
def deleteSecret(request, post_id):
    Secret.objects.deleteSecret(post_id)
    return redirect('secret:home')

'''calls method to like a secret'''
def likeSecret(request, post_id):
    Secret.objects.likeSecret(request.session['user']['id'], post_id)
    return redirect('secret:home')

'''renders page displaying most popular secrets'''
def mostPopular(request):
    try:
        request.session['user']
    except KeyError:
        return redirect(reverse('login:login'))
    context = {
        'posts': Secret.objects.getPopular()
    }
    return render(request, 'dojo_secret/popular.html', context)

apps/validation/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect, reverse
from django.contrib import messages
from django.forms.models import model_to_dict
from models import User
# Create your views here.
'''Landing page w/ 2 forms (login and registration)'''
def index(request):
    return render(request, 'validation/index.html')

'''Call method to creat a new user or login user and enter session'''
def validateUser(request, route):
    if request.method == 'POST':
        if route == 'reg':
            newUser = User.objects.newUser(request.POST)
        else:
            newUser = User.objects.validateUser(request.POST)
        # print '-' * 80
        # print 'newUser',newUser
        if not newUser[1]:
            for x in range(len(newUser[0])):
                messages.error(request, newUser[0][x])
            return redirect(reverse('login:login'))
        else:
            request.session['user'] = model_to_dict(newUser[0])
            return redirect(reverse('secret:home'))
    else:
        return redirect(reverse('login:login'))

'''Call method to exit session'''
def logOut (request):
    request.session.clear()
    return redirect(reverse('login:login'))

apps/dojo_secret/templates/dojo_secret/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Dojo Secrets</title>
  </head>
  <body>
    <h1>Hello, {{request.session.user.first_name}}</h1>
    <a href="{% url 'login:logout' %}">logout</a>
    <form class="" action="{% url 'secret:post' %}" method="post">
      {% csrf_token%}
      <input type="hidden" name="user_id" value="{{request.session.user.id}}">
      <textarea name="secret" rows="8" cols="80"></textarea>
      <input type="submit" name="submit" value="Post">
    </form>
    <a href="{% url 'secret:popular'%}">Go back</a>
    <h2>Recent Secrets</h2>
    {% for post in posts %}
    <p>{{post.secrets}} Created {{ post.created_at|timesince}} ago. Number of likes: {{post.numLikes}}{% if not post.writer.id == request.session.user.id %} <a href="{% url 'secret:like' post.id %}">Like</a>{% else %} <a href="{% url 'secret:delete' post.id %}">Delete</a>{% endif %}</p>
    {% if request.session.user.id in post.likes %} True {% endif %}
    {% endfor %}
  </body>
</html>

apps/dojo_secret/templates/dojo_secret/popular.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Dojo Secrets</title>
  </head>
  <body>
    <h1>Hello, {{request.session.user.first_name}}</h1>
    <a href="{% url 'login:logout' %}">logout</a>
    <h2>Most Popular Secrets</h2>
    {% for post in posts %}
    <p>{{post.secrets}} Created {{ post.created_at|timesince}} ago. Number of likes: {{post.numLikes}}{% if not post.writer.id == request.session.user.id %} <a href="{% url 'secret:like' post.id %}">Like</a>{% else %} <a href="{% url 'secret:delete' post.id %}">Delete</a>{% endif %}</p>
    {% endfor %}
    <a href="{% url 'secret:home'%}">Go back</a>
  </body>
</html>

apps/validation/templates/validation/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Dojo Secrets Login</title>
  </head>
  <body>
    <div class="">
      <h3>Register</h3>
      <form class="" action="{% url 'login:validate' 'reg' %}" method="post">
        {% csrf_token %}
        <label for="frst_name">First Name: </label><input type="text" name="first_name" value="">
        <label for="last_name">Last Name: </label><input type="text" name="last_name" value="">
        <label for="email">E-mail: </label><input type="text" name="email" value="">
        <label for="pw">Password: </label><input type="password" name="pw" value="">
        <label for="pwConf">Confirm Password: </label><input type="password" name="pwConf" value="">
        <input type="submit" name="register" value="Register">
      </form>
    </div>
    <div class="">
      <h3>Login</h3>
      <form class="" action="{% url 'login:validate' 'login' %}" method="post">
        {% csrf_token %}
        <label for="email">E-mail: </label><input type="text" name="email" value="">
        <label for="pw">Password: </label><input type="password" name="pw" value="">
        <input type="submit" name="validate" value="Login">
      </form>
    </div>
    <div class="">
      {% if messages %}
      <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{message}}</li>
        {% endfor %}
      </ul>
      {% endif %}
    </div>
  </body>
</html>